name: Publish Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  push_fpm_to_registry:
    runs-on: ubuntu-latest
    name: Build "evoweb/syncthing-linker:${{ github.ref_name }}" and push it to repository

    steps:
      - uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: evoweb/syncthing-linker

      - name: Build Docker image
        id: build
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          load: true
          build-args: VERSION=${{ github.ref_name }}
          tags: evoweb/syncthing-linker:latest,evoweb/syncthing-linker:${{ github.ref_name }}

      - name: Test the build image
        if: steps.build.outputs.imageid != ''
        run: |
          docker run --rm evoweb/syncthing-linker:latest ls -la

      - name: Log in to Docker Hub
        if: steps.build.outputs.imageid != '' && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        if: steps.build.outputs.imageid != '' && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: VERSION=${{ matrix.version }}
          tags: evoweb/syncthing-linker:latest,evoweb/syncthing-linker:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
